name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      
    - name: Install the project
      run: uv sync --locked --all-extras --dev
      
    - name: Run unit tests
      run: |
        python3 -m unittest discover -s src -v

    - name: Check for formatting issues with black
      run: |
        black --check $(git ls-files '*.py')
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
